apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: test-storageclass 
provisioner: kubernetes.io/rbd
parameters:
    monitors: 192.168.100.117:6789
    adminId: admin 
    adminSecretName: ceph-secret
    adminSecretNamespace: kube-system
    pool: data
    userId: admin
    userSecretName: ceph-secret 
