apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: test-sc-pvc
    annotations:
        volume.beta.kubernetes.io/storage-class: test-storageclass
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 2Gi
