apiVersion: v1
kind: PersistentVolume
metadata:
    name: test-pv
spec:
    capacity:
        storage: 5Gi
    accessModes:
    - ReadWriteOnce
    rbd:
        monitors:
        - 192.168.100.117:6789
        pool: data
        image: data
        user: admin
        secretRef:
            name: ceph-secret 
        fsType: xfs
        readOnly: false
    persistentVolumeReclaimPolicy: Recycle
