apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: demo
spec:
    replicas: 3
    template:
        metadata:
            labels:
                app: demo 
        spec:
            containers:
            - name: demo
              image: mritd/demo
              ports:
              - containerPort: 80
              volumeMounts:
              - mountPath: "/data/"
                name: data
            volumes:
            - name: data
              persistentVolumeClaim:
                claimName: test-pvc

